### ISSUE TITLE
multiple joysticks overlap

### ISSUE THREAD

**Issue by zosky** [Dinir/gamepad-viewer#4]
i'm teaching my 4yr old how to game and this takes it to the next level. thank you!! 

with 2 pads & fixed positioning in the css ... both controllers are overlapped. this feels unintended rather than intentional ?

![image](https://user-images.githubusercontent.com/112049/79171104-35058080-7dbf-11ea-8ebd-7824bda591eb.png)

i rejigged things to match our quarantined physical world _(logitech wireless rumblePad)_ nothing fancy. what you've done here is awesome. thanks again. 

![image](https://user-images.githubusercontent.com/112049/79173207-de9b4080-7dc4-11ea-8a0c-1e475456a600.png)

**Comment by Dinir** [comment]
You converted it into a much more functional shape! 😃 I don't expect many people to be interested in overlays like this, so I am grateful for you finding it useful.

The code was meant for only one gamepad, because in the day I was writing it I didn't expect me to have any more than one gamepad at a moment. It was due to my short sight, I'd rather say. 😅

- - -

I am currently working on a new version, and although it has some features missing it's currently better than the last release at the moment, and will show multiple gamepads properly. So I suggest you to try the new version.

The [striked line in the README](https://github.com/Dinir/gamepad-viewer#how-to-use) has a '[hosted webpage](https://dinir.github.io/gamepad-viewer/gamepadviewer.html)' link, which actually goes to the new version in development.

For now it should be hosted before a user can use it, so you can download the repository then host it on a local server or use the link instead. I hid the link under a strikeline because it's basically unfinished, but for 'displaying multiple gamepads' it will be enough.



Thanks again for the interest and opening the issue! I hope this new version helps.
